<?php

namespace App\Enums;

enum PermissionEnum: string
{
    /** AUTH */
    case AUTH_UPDATE = 'AUTH_UPDATE';

    /** ROLE */
    case ROLE_INDEX = 'ROLE_INDEX';
    case ROLE_SHOW = 'ROLE_SHOW';
    case ROLE_STORE = 'ROLE_STORE';
    case ROLE_UPDATE = 'ROLE_UPDATE';
    case ROLE_DESTROY = 'ROLE_DESTROY';

    /** PERMISSION */
    case PERMISSION_INDEX = 'PERMISSION_INDEX';
    case PERMISSION_SHOW = 'PERMISSION_SHOW';

    /** USER */
    case USER_INDEX = 'USER_INDEX';
    case USER_SHOW = 'USER_SHOW';
    case USER_STORE = 'USER_STORE';
    case USER_UPDATE = 'USER_UPDATE';
    case USER_DESTROY = 'USER_DESTROY';

    /** CASHIER */
    case CASHIER_INDEX = 'CASHIER_INDEX';
    case CASHIER_SHOW = 'CASHIER_SHOW';
    case CASHIER_STORE = 'CASHIER_STORE';
    case CASHIER_UPDATE = 'CASHIER_UPDATE';
    case CASHIER_DESTROY = 'CASHIER_DESTROY';

    /** SHOP */
    case SHOP_INDEX = 'SHOP_INDEX';
    case SHOP_SHOW = 'SHOP_SHOW';
    case SHOP_STORE = 'SHOP_STORE';
    case SHOP_UPDATE = 'SHOP_UPDATE';
    case SHOP_DESTROY = 'SHOP_DESTROY';

    /** CATEGORY */
    case CATEGORY_INDEX = 'CATEGORY_INDEX';
    case CATEGORY_SHOW = 'CATEGORY_SHOW';
    case CATEGORY_STORE = 'CATEGORY_STORE';
    case CATEGORY_UPDATE = 'CATEGORY_UPDATE';
    case CATEGORY_DESTROY = 'CATEGORY_DESTROY';

    /** ITEM */
    case ITEM_INDEX = 'ITEM_INDEX';
    case ITEM_SHOW = 'ITEM_SHOW';
    case ITEM_STORE = 'ITEM_STORE';
    case ITEM_UPDATE = 'ITEM_UPDATE';
    case ITEM_DESTROY = 'ITEM_DESTROY';

    /** MATERIAL */
    case MATERIAL_INDEX = 'MATERIAL_INDEX';
    case MATERIAL_SHOW = 'MATERIAL_SHOW';
    case MATERIAL_STORE = 'MATERIAL_STORE';
    case MATERIAL_UPDATE = 'MATERIAL_UPDATE';
    case MATERIAL_DESTROY = 'MATERIAL_DESTROY';

    /** TRANSFER_ITEM */
    case TRANSFER_ITEM_INDEX = 'TRANSFER_ITEM_INDEX';
    case TRANSFER_ITEM_SHOW = 'TRANSFER_ITEM_SHOW';
    case TRANSFER_ITEM_STORE = 'TRANSFER_ITEM_STORE';
    case TRANSFER_ITEM_UPDATE = 'TRANSFER_ITEM_UPDATE';
    case TRANSFER_ITEM_DESTROY = 'TRANSFER_ITEM_DESTROY';

    /** TRANSFER_MATERIAL */
    case TRANSFER_MATERIAL_INDEX = 'TRANSFER_MATERIAL_INDEX';
    case TRANSFER_MATERIAL_SHOW = 'TRANSFER_MATERIAL_SHOW';
    case TRANSFER_MATERIAL_STORE = 'TRANSFER_MATERIAL_STORE';
    case TRANSFER_MATERIAL_UPDATE = 'TRANSFER_MATERIAL_UPDATE';
    case TRANSFER_MATERIAL_DESTROY = 'TRANSFER_MATERIAL_DESTROY';

    /** TABLE_NUMBER */
    case TABLE_NUMBER_INDEX = 'TABLE_NUMBER_INDEX';
    case TABLE_NUMBER_SHOW = 'TABLE_NUMBER_SHOW';
    case TABLE_NUMBER_STORE = 'TABLE_NUMBER_STORE';
    case TABLE_NUMBER_UPDATE = 'TABLE_NUMBER_UPDATE';
    case TABLE_NUMBER_DESTROY = 'TABLE_NUMBER_DESTROY';

    /** ORDER */
    case ORDER_INDEX = 'ORDER_INDEX';
    case ORDER_SHOW = 'ORDER_SHOW';
    case ORDER_STORE = 'ORDER_STORE';
    case ORDER_UPDATE = 'ORDER_UPDATE';
    case ORDER_DESTROY = 'ORDER_DESTROY';

    /** PAYMENT */
    case PAYMENT_INDEX = 'PAYMENT_INDEX';
    case PAYMENT_SHOW = 'PAYMENT_SHOW';
    case PAYMENT_STORE = 'PAYMENT_STORE';
    case PAYMENT_UPDATE = 'PAYMENT_UPDATE';
    case PAYMENT_DESTROY = 'PAYMENT_DESTROY';

    /** CUSTOMER */
    case CUSTOMER_INDEX = 'CUSTOMER_INDEX';
    case CUSTOMER_SHOW = 'CUSTOMER_SHOW';
    case CUSTOMER_STORE = 'CUSTOMER_STORE';
    case CUSTOMER_UPDATE = 'CUSTOMER_UPDATE';
    case CUSTOMER_DESTROY = 'CUSTOMER_DESTROY';

    /** INVOICE */
    case INVOICE_INDEX = 'INVOICE_INDEX';
    case INVOICE_SHOW = 'INVOICE_SHOW';
    case INVOICE_STORE = 'INVOICE_STORE';
    case INVOICE_UPDATE = 'INVOICE_UPDATE';
    case INVOICE_DESTROY = 'INVOICE_DESTROY';

    /** INVOICE_ITEM */
    case INVOICE_ITEM_INDEX = 'INVOICE_ITEM_INDEX';
    case INVOICE_ITEM_SHOW = 'INVOICE_ITEM_SHOW';
    case INVOICE_ITEM_STORE = 'INVOICE_ITEM_STORE';
    case INVOICE_ITEM_UPDATE = 'INVOICE_ITEM_UPDATE';
    case INVOICE_ITEM_DESTROY = 'INVOICE_ITEM_DESTROY';

    /** SALE_MAN_WORKING_TIME */
    case SALE_MAN_WORKING_TIME_INDEX = 'SALE_MAN_WORKING_TIME_INDEX';
    case SALE_MAN_WORKING_TIME_SHOW = 'SALE_MAN_WORKING_TIME_SHOW';
    case SALE_MAN_WORKING_TIME_STORE = 'SALE_MAN_WORKING_TIME_STORE';
    case SALE_MAN_WORKING_TIME_UPDATE = 'SALE_MAN_WORKING_TIME_UPDATE';
    case SALE_MAN_WORKING_TIME_DESTROY = 'SALE_MAN_WORKING_TIME_DESTROY';
}
